### PR TITLE
docs: expand abbrevs

### PR DESCRIPTION
**Pull request by bwendlandt-intel**
## PR Checklist

- [x] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [x] Have viewed and verified edits in rendered form ensuring proper formatting

## What are you changing?

- Few abbrev definition changes and add additional ones
- Spelling/Style edits to make sure it matches abbrevs

### CODE REVIEW

**Comment by bwendlandt-intel** [comment]
@kimberlyxdavis I changed a few of your definitions and expanded across all docs.  Changed from definition focused around GSG to more general to account. We can hop on a call.

**Review by kimberlyxdavis — CHANGES_REQUESTED** [review]
In my PR, I took out a lot of the extraneous hyperlinks. I noticed that these files still contain them. I think we should make a decision. One way or the other, to be consistent. Or, I could approve this and then we could work on that effort later.

**Review by kimberlyxdavis — CHANGES_REQUESTED** [review]
In my PR, I took out a lot of the extraneous hyperlinks. I noticed that these files still contain them. I think we should make a decision. One way or the other, to be consistent. Or, I could approve this and then we could work on that effort later.

**Comment by bwendlandt-intel** [comment]
> In my PR, I took out a lot of the extraneous hyperlinks. I noticed that these files still contain them. I think we should make a decision. One way or the other, to be consistent. Or, I could approve this and then we could work on that effort later.

As in removing the references to the old Glossary?

**Review by kimberlyxdavis — APPROVED** [review]
Great.

**Pull request merged**
