### PR TITLE
using submodules for local setup

### PR DESCRIPTION
**Pull request by brianosburn-intel**
## PR Checklist

- [x ] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [x ] Have viewed and verified edits in rendered form ensuring proper formatting

## What are you changing?

updated to use submodules for repos

### CODE REVIEW

**Comment by rsdmike** [comment]
@kimberlyxdavis @bwendlandt-intel What do ya'll thinking about collapsing install RPS and install MPS to the same doc? I think it simplifies things and avoid confusion.

**Review by kimberlyxdavis — COMMENTED** [review]
Brian:
installMPS & installRPS.md: 
I understand the urge to change the heading to "Clone the OpenAMT Cloud Toolkit." We have the duplicate statements of "Clone the Repository" and "To clone the repositories" due to trying to follow a structure.

However, when we first mention OpenAMT in text we have to spell it out. Plus we're cloning a portion of the toolkit. 

Would it help to change it to "Clone the Microservice", as that is what we are really doing? 

Plus it looks as if it's the same instruction. 

I also like Mike's idea of collapsing if it doesn't mess up anything else.

**Comment by bwendlandt-intel** [comment]
Quick Nitpick on Naming: I'll leave it to Kimberly to work out which is the best title for the sections.  Just a reminder that the legal-approved name is 'Open AMT Cloud Toolkit'. Two words, not one (OpenAMT vs Open AMT).  I'd also argue that we are alright on using the abbreviated version since the long version is seen in the site header, introduced on the home page, and used in the current pages diagram.

Thoughts on MPS/RPS merge: I'm a bit more hesitant to merge MPS/RPS steps for the local flow unless there is some possible simplification that you guys can do around reducing the .mpsrc and app.config.js config steps.  We initially had them placed together, but through DX people struggled to identify what MPS vs RPS did when questioned later in the flow.  My concern is that the brief, but reasonable RPS intro and arch diagram become too easy to ignore after scrolling through the large snippets for MPS config steps. Thoughts?

**Review by kimberlyxdavis — COMMENTED** [review]
I think BW's concerns are legitimate and good points. 

I was just thinking during lunch that I will have to change the diagram if we collapse it into one file. But if we don't change it into one file, I think it becomes really confusing because the git clone instruction for both MPS and RPS looks the same. So, it's quite a conundrum. 

Proposal for one file: InstallMicroservices.md
"Install Microservices"
New Diagram
"Clone the Microservices Repositories" 
Then we'd have be really clear about MPS and RPS-- that's what we're attempting to install.

Can anyone see any side effects? I'm looking at both files now. I'm starting to hate this idea. It's a bit terrifying actually.

This afternoon, I had  asked Brian why the git clone looks the same. Brian, I hope you don't mind. I'm dropping it into this discussion:

"That repo has git submodules that reference the other repos.. when the recursive flag is used, it also checks out mps, rps, docs, sample-web-ui, and ui-toolkit.. that way the developer doesn’t have to checkout each repo manually and it also preserves the folder structure."

BW and Mike, you probably already know this bit. I found it confusing because I'm not as familiar with git. 

Apologies if I've introduced a non sequitur. It just confused me as a non-developer on the project.
KD

**Comment by bwendlandt-intel** [comment]
> 
> "That repo has git submodules that reference the other repos.. when the recursive flag is used, it also checks out mps, rps, docs, sample-web-ui, and ui-toolkit.. that way the developer doesn’t have to checkout each repo manually and it also preserves the folder structure."
> 

For the GSG flow now, we should be able to remove the subsequent clone commands after the initial one in the MPS. We might want to clarify language that they are cloning the whole toolkit rather than just MPS, which I think is what Brian was trying to do as part of this PR. In the RPS/RPC sections, we only need to make sure steps are there to help people navigate to the correct directory rather than clone again. Does that clarify things?

**Review by kimberlyxdavis — COMMENTED** [review]
BW, yes. Makes sense.

It seems to go beyond MPS and RPS as we cloning the entire thing. Indeed. Looking at the Overview file, I find it suddenly makes less sense if we combine the InstallMPS and InstallRPS. It reads weirdly. 

Perhaps we should let Brian check it in as is, and then you and I should work on what we want to do to the navigation and supporting text.

I like the idea of discussing concerns and side effects here, but I don't like the idea of designing it here.

**Comment by rsdmike** [comment]
I'm starting to see the need for a quick start -- a doc that has a single page that gets everything up and running. Which then can lead to the microservices and the role each one has. I'm really trying to get us to a 1-2-3 GO! scenario for the 1.1 release that doesn't have 5-7 pages of intro/documentation. What do ya think of that?

**Review by kimberlyxdavis — COMMENTED** [review]
I love that idea. I see it as a distinct possibility now that we're cloning the whole thing.

KD

**Review by kimberlyxdavis — APPROVED** [review]
Hi Brian. 

These changes look fine. BW and I are going to create more restructuring later. Please move forward.

KD

**Comment by brianosburn-intel** [comment]
thank you for reviewing!

**Comment by rsdmike** [comment]
@brianosburn-intel please amend your commit message to follow conventional commits so we can merge this.

**Pull request merged**
